desc "Create Users"
task create_bulk_users: [:environment] do
  names = [
    'Eloise Palmer',
    'Sheryl Murray',
    'Kelly Reese',
    'Judy Gordon',
    'Felix Ortiz',
    'Jermaine Welch',
    'Clint Sims',
    'James Olson',
    'Fred Webster',
    'Laverne Douglas',
    'Alexander Simon',
    'Nicolas Roberson',
    'Janet Patrick',
    'Toby Nelson',
    'Francisco Cooper',
    'Alberta Bates',
    'Gary Fowler',
    'Stella Nguyen',
    'Allan Bridges',
    'Jon Dennis',
    'Myron Marsh',
    'Kenneth Bennett',
    'Eric Carson',
    'Joanne Caldwell',
    'Sylvia Beck',
    'Angela Soto',
    'Jana Ray',
    'Nichole Parker',
    'Gerard Cole',
    'Alice Myers',
    'Kathy Floyd',
    'Grady Manning',
    'Alicia Montgomery',
    'Megan Rogers',
    'Claudia Smith',
    'Rex Hill',
    'Leland Thornton',
    'Jackie Romero',
    'Ellen Snyder',
    'Laurence Alvarez',
    'Bruce Rose',
    'Cora James',
    'Terrence Singleton',
    'Ervin Pena',
    'Rosalie Herrera',
    'Leticia Bowen',
    'Jessie Love',
    'Victor Hughes',
    'Louise Valdez',
    'Virginia Banks',
    'Eleanor Franklin',
    'Lynn Lloyd',
    'Miguel Ellis',
    'Sophie Wong',
    'Kristin Adams',
    'Suzanne Gregory',
    'Mona Reid',
    'Rick Cohen',
    'Emma Richards',
    'Krista Tran',
    'Daryl Watts',
    'Tasha Coleman',
    'Kristy Garrett',
    'Boyd Nunez',
    'Lamar Young',
    'Eunice Keller',
    'Florence Patton',
    'Melanie Rhodes',
    'Tony Briggs',
    'Marilyn King',
    'Timmy Reynolds',
    'Mable Buchanan',
    'Lynn Hayes',
    'Rodney Santos',
    'Delores Pope',
    'Grace Joseph',
    'Essie French',
    'Doyle Stokes',
    'Chester Garner',
    'Roy Mcdaniel',
    'Winston Shelton',
    'Perry Hardy',
    'Roland Mckinney',
    'Jody Sparks',
    'Mandy Cannon',
    'Blanche Holmes',
    'Mack Davis',
    'Simon Griffith',
    'Leslie Robbins',
    'Amelia Allison',
    'Shannon Watson',
    'Earl Fletcher',
    'Sonia Robinson',
    'Bradford Day',
    'Daisy Campbell',
    'Opal Gonzalez',
    'Neil Curtis',
    'Ben Patterson',
    'Jessie Morris',
    'Juanita Scott',
    'Diana Young',
    'Sonia Weaver',
    'Omar Jennings',
    'Alan Francis',
    'Patrick Norman',
    'Kristopher Phelps',
    'Morris Allison',
    'Cecil Lamb',
    'Lloyd Mccarthy',
    'Jessie Welch',
    'Patsy Harrington',
    'Teresa Gonzalez',
    'Joanna Davidson',
    'Joanne Adams',
    'Monica Bryan',
    'Enrique Dean',
    'Wade Rose',
    'Dwayne Russell',
    'Leonard Diaz',
    'Israel Rice',
    'Henrietta Miller',
    'Peggy Tyler',
    'Irving Blake',
    'Jay Massey',
    'Jeanette Curry',
    'Alexandra Sanders',
    'Todd Cole',
    'Cesar Wilkins',
    'Ramon Thornton',
    'Rudolph Casey',
    'Troy Carpenter',
    'Timothy Herrera',
    'Hattie Hogan',
    'Joel Terry',
    'Kevin Turner',
    'Horace Conner',
    'Wanda Hansen',
    'Rochelle Wise',
    'Bonnie Luna',
    'Gene Rodgers',
    'Adrienne Fernandez',
    'Mattie Watson',
    'Stacy Valdez',
    'Mitchell Salazar',
    'Naomi Ramirez',
    'Archie Parker',
    'Nelson Patton',
    'John Andrews',
    'Maxine Yates',
    'Abel Morrison',
    'Tom Hanson',
    'Don Kelley',
    'Joann Richardson',
    'Ted Hamilton',
    'Leslie Perkins',
    'Cheryl Newton',
    'Lindsey Hardy',
    'Samuel Poole',
    'Megan Wade',
    'Kristina Sparks',
    'Sophia Mcdaniel',
    'Mamie Mccormick',
    'Gary Lawrence',
    'Samantha Cortez',
    'Cecelia Strickland',
    'Terrell Romero',
    'Aubrey Collier',
    'Sharon Bass',
    'Elisa Anderson',
    'Stewart Alvarez',
    'Taylor Greer',
    'Terence Elliott',
    'Brenda Snyder',
    'Carol Vaughn',
    'Rafael Tate',
    'Julia Padilla',
    'Eugene Lynch',
    'Robyn Webster',
    'Lindsay Stone',
    'Paul Sullivan',
    'Wilson Jenkins',
    'Terry Evans',
    'Dean Wong',
    'Esther Holmes',
    'Dianne Pena',
    'Fannie Simmons',
    'Jennifer Wilkerson',
    'Belinda Powers',
    'Dianna Beck',
    'Terrence Carter',
    'Erma Cooper',
    'Carlos Clayton',
    'Paulette Baldwin',
    'Yvonne Lindsey',
    'Carole Mccoy',
    'Sarah Arnold',
    'Catherine Garza',
    'Oscar Little',
    'Ernest Morton',
    'Billy Baker'
  ]

  student = Role.where(:code => 'student').first
  parent = Role.where(:code => 'parent').first

  names.each do |name|
    begin
        u = User.new
        u.name = name
        u.email = name.parameterize + '@gmail.com'
        u.password = 'password'
        u.password_confirmation = 'password'
        u.roles.append(student)
        u.save!

        last_name = name.split[1]

        ['Bob', 'Alice'].each do |first_name|
          p1 = User.new
          p1.name = first_name + ' ' + last_name
          p1.email = p1.name.parameterize + '@gmail.com'
          p1.password = 'password'
          p1.password_confirmation = 'password'
          p1.roles.append(parent)
          p1.save!
        end
    rescue StandardError => e
        p e.message
    end
  end
end